# Generated by Django 5.2 on 2025-04-22 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('uuid', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='Enter your email', max_length=320)),
                ('sign_up_time', models.DateTimeField()),
                ('age_group', models.CharField(choices=[('0', 'Less than 13'), ('1', '13 - 17'), ('2', '18 - 24'), ('3', '25 - 34'), ('4', '35 - 44'), ('5', '45 - 64'), ('6', 'More than 65'), ('prefer_not', 'Prefer not to say')], help_text='Select your age group')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not', 'Prefer not to say')], help_text='Select your gender group')),
            ],
        ),
    ]
