# Generated by Django 5.2 on 2025-04-22 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_rename_users_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age_group',
            field=models.CharField(choices=[('<13', 'Less than 13'), ('13-17', '13 - 17'), ('18-24', '18 - 24'), ('25-34', '25 - 34'), ('35-44', '35 - 44'), ('45-64', '45 - 64'), ('>65', 'More than 65'), ('prefer_not', 'Prefer not to say')], help_text='Select your age group'),
        ),
    ]
