# Generated by Django 5.2 on 2025-04-22 03:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0004_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sign_up_time',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
    ]
