# Generated by Django 5.2 on 2025-04-23 03:17

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0006_alter_user_email_alter_user_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('walk', 'Walking'), ('bike', 'Cycling'), ('bus', 'Bussing')])),
                ('log_time', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('distance', models.CharField(choices=[('500', '0.5km'), ('1000', '1km'), ('2500', '2.5km'), ('5000', '5km'), ('10000', '10km'), ('25000', '25km'), ('50000', '50km')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.user')),
            ],
        ),
    ]
