# Generated by Django 5.2 on 2025-04-23 02:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('key', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(editable=False)),
                ('mode', models.CharField(choices=[('walk', 'Walking'), ('bike', 'Cycling'), ('bus', 'Bussing')])),
                ('log_time', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('distance', models.PositiveIntegerField(verbose_name=[(500, '0.5km'), (1000, '1km'), (2500, '2.5km'), (5000, '5km'), (10000, '10km'), (25000, '25km'), (50000, '50km')])),
            ],
        ),
    ]
