# Generated by Django 5.2 on 2025-04-23 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0003_alter_trip_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='distance',
            field=models.CharField(choices=[('500', '0.5km'), ('1000', '1km'), ('2500', '2.5km'), ('5000', '5km'), ('10000', '10km'), ('25000', '25km'), ('50000', '50km')]),
        ),
        migrations.AlterField(
            model_name='trip',
            name='uuid',
            field=models.UUIDField(),
        ),
    ]
