# Generated by Django 5.2 on 2025-04-23 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0004_alter_trip_distance_alter_trip_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='uuid',
        ),
    ]
