# Generated by Django 5.2 on 2025-04-23 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0005_remove_trip_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='distance',
        ),
        migrations.AddField(
            model_name='trip',
            name='uuid',
            field=models.UUIDField(default='a0657927-fa0d-46cc-8059-c95515fe0aee'),
            preserve_default=False,
        ),
    ]
