# Generated by Django 5.2 on 2025-04-23 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0006_remove_trip_distance_trip_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='log_time',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='mode',
        ),
    ]
