# Generated by Django 5.2 on 2025-04-23 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0007_remove_trip_log_time_remove_trip_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='key',
        ),
        migrations.AddField(
            model_name='trip',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
