# Generated by Django 5.2 on 2025-04-23 03:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0008_remove_trip_key_trip_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='distance',
            field=models.CharField(choices=[('500', '0.5km'), ('1000', '1km'), ('2500', '2.5km'), ('5000', '5km'), ('10000', '10km'), ('25000', '25km'), ('50000', '50km')], default='5000'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='log_time',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AddField(
            model_name='trip',
            name='mode',
            field=models.CharField(choices=[('walk', 'Walking'), ('bike', 'Cycling'), ('bus', 'Bussing')], default='bus'),
            preserve_default=False,
        ),
    ]
