# Generated by Django 5.2 on 2025-04-23 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0009_trip_distance_trip_log_time_trip_mode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trip',
        ),
    ]
