# Generated by Django 5.2 on 2025-06-14 08:32

import datetime
import django.db.models.deletion
import markdownx.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('main', '0001_initial'), ('main', '0002_trip_text_response_alter_trip_distance_and_more'), ('main', '0003_alter_trip_mode'), ('main', '0004_alter_trip_text_response'), ('main', '0005_deleteduser_alter_trip_distance_deletedtrip'), ('main', '0006_alter_deletedtrip_user'), ('main', '0007_deleteduser_emissions_saved_user_emissions_saved'), ('main', '0008_remove_deleteduser_gender_remove_user_gender'), ('main', '0009_employer'), ('main', '0010_region'), ('main', '0011_user_distance_user_employer_user_region_user_vehicle'), ('main', '0012_user_name'), ('main', '0013_deleteduser_distance_deleteduser_employer_and_more'), ('main', '0014_remove_trip_distance'), ('main', '0015_remove_deletedtrip_distance'), ('main', '0016_deletedtrip_quantity_trip_quantity'), ('main', '0017_all_employer_emissions_saved_region_emissions_saved_and_more'), ('main', '0018_post'), ('main', '0019_user_logged_this_week_alter_post_content_and_more')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('name', models.CharField(primary_key=True, serialize=False, unique=True)),
                ('emissions_saved', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('name', models.CharField(primary_key=True, serialize=False, unique=True)),
                ('emissions_saved', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=320, unique=True)),
                ('sign_up_time', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('age_group', models.CharField(choices=[('<13', 'Less than 13'), ('13-17', '13 - 17'), ('18-24', '18 - 24'), ('25-34', '25 - 34'), ('35-44', '35 - 44'), ('45-64', '45 - 64'), ('>65', 'More than 65'), ('prefer_not', 'Prefer not to say')])),
                ('emissions_saved', models.PositiveIntegerField(default=0)),
                ('distance', models.PositiveIntegerField(choices=[(500, '0.5km'), (1000, '1km'), (2500, '2.5km'), (5000, '5km'), (10000, '10km'), (25000, '25km'), (50000, '50km')], default=2500)),
                ('employer', models.ForeignKey(default='None / Other / Prefer Not To Say', on_delete=django.db.models.deletion.SET_DEFAULT, to='main.employer')),
                ('region', models.ForeignKey(default='Other', on_delete=django.db.models.deletion.SET_DEFAULT, to='main.region')),
                ('vehicle', models.PositiveIntegerField(choices=[(243, 'Petrol'), (265, 'Diesel'), (192, 'Hybrid'), (98, 'Plug-in Hybrid'), (19, 'Electric'), (243, "Other / Don't know")], default=243)),
                ('name', models.CharField(default='I am John Balls, Slayer of Balls', max_length=20)),
                ('logged_this_week', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DeletedUser',
            fields=[
                ('uuid', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('sign_up_time', models.DateTimeField(editable=False)),
                ('age_group', models.CharField(choices=[('<13', 'Less than 13'), ('13-17', '13 - 17'), ('18-24', '18 - 24'), ('25-34', '25 - 34'), ('35-44', '35 - 44'), ('45-64', '45 - 64'), ('>65', 'More than 65'), ('prefer_not', 'Prefer not to say')], help_text='Select your age group')),
                ('emissions_saved', models.PositiveIntegerField(default=0)),
                ('distance', models.PositiveIntegerField(choices=[(500, '0.5km'), (1000, '1km'), (2500, '2.5km'), (5000, '5km'), (10000, '10km'), (25000, '25km'), (50000, '50km')], default=500)),
                ('employer', models.ForeignKey(default='None / Other / Prefer Not To Say', on_delete=django.db.models.deletion.SET_DEFAULT, to='main.employer')),
                ('region', models.ForeignKey(default='Other', on_delete=django.db.models.deletion.SET_DEFAULT, to='main.region')),
                ('vehicle', models.PositiveIntegerField(choices=[(243, 'Petrol'), (265, 'Diesel'), (192, 'Hybrid'), (98, 'Plug-in Hybrid'), (19, 'Electric'), (243, "Other / Don't know")], default=20)),
            ],
        ),
        migrations.CreateModel(
            name='All',
            fields=[
                ('name', models.CharField(primary_key=True, serialize=False, unique=True)),
                ('emissions_saved', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DeletedTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(blank=True, choices=[('walk', 'Walk'), ('bike', 'Bike / Scooter'), ('bus', 'Bus'), ('ev', 'EV'), ('carpool', 'Carpool')], null=True)),
                ('log_time', models.DateTimeField(editable=False)),
                ('text_response', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.deleteduser')),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(blank=True, choices=[('walk', 'Walk'), ('bike', 'Bike / Scooter'), ('bus', 'Bus'), ('ev', 'EV'), ('carpool', 'Carpool')], null=True)),
                ('log_time', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
                ('text_response', models.TextField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='For system use only - will not be displayed to users.', max_length=30)),
                ('content', markdownx.models.MarkdownxField(help_text='Use markdown to style post (https://www.markdownguide.org/basic-syntax/). Do not use single hashtag heading (#) as is too large. Drag images in to add, as that will automatically store the image.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
