# Generated by Django 5.2 on 2025-04-23 03:49

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='Enter your email', max_length=320, unique=True)),
                ('sign_up_time', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('age_group', models.CharField(choices=[('<13', 'Less than 13'), ('13-17', '13 - 17'), ('18-24', '18 - 24'), ('25-34', '25 - 34'), ('35-44', '35 - 44'), ('45-64', '45 - 64'), ('>65', 'More than 65'), ('prefer_not', 'Prefer not to say')], help_text='Select your age group')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not', 'Prefer not to say')], help_text='Select your gender')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('walk', 'Walking'), ('bike', 'Cycling'), ('bus', 'Bussing')])),
                ('log_time', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('distance', models.PositiveIntegerField(choices=[(500, '0.5km'), (1000, '1km'), (2500, '2.5km'), (5000, '5km'), (10000, '10km'), (25000, '25km'), (50000, '50km')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
        ),
    ]
