# Generated by Django 5.2 on 2025-04-23 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='text_response',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='distance',
            field=models.PositiveIntegerField(choices=[(0, '0'), (500, '0.5km'), (1000, '1km'), (2500, '2.5km'), (5000, '5km'), (10000, '10km'), (25000, '25km'), (50000, '50km')]),
        ),
        migrations.AlterField(
            model_name='trip',
            name='mode',
            field=models.CharField(choices=[('walk', 'Walking'), ('bike', 'Cycling'), ('bus', 'Bussing')], null=True),
        ),
    ]
