# Generated by Django 5.2 on 2025-04-23 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_trip_text_response_alter_trip_distance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='mode',
            field=models.CharField(blank=True, choices=[('walk', 'Walking'), ('bike', 'Cycling'), ('bus', 'Bussing')], null=True),
        ),
    ]
