# Generated by Django 5.2 on 2025-04-23 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_trip_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='text_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
