# Generated by Django 5.2 on 2025-04-23 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_deletedtrip_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='deleteduser',
            name='emissions_saved',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='emissions_saved',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
