# Generated by Django 5.2 on 2025-05-17 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_deleteduser_emissions_saved_user_emissions_saved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deleteduser',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
    ]
