# Generated by Django 5.2 on 2025-05-17 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_employer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('name', models.CharField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
