# Generated by Django 5.2 on 2025-05-17 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_user_distance_user_employer_user_region_user_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='I am John Balls, Slayer of Balls', max_length=20),
            preserve_default=False,
        ),
    ]
