# Generated by Django 5.2 on 2025-05-17 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='deleteduser',
            name='distance',
            field=models.PositiveIntegerField(choices=[(500, '0.5km'), (1000, '1km'), (2500, '2.5km'), (5000, '5km'), (10000, '10km'), (25000, '25km'), (50000, '50km')], default=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deleteduser',
            name='employer',
            field=models.ForeignKey(default='None / Other / Prefer Not To Say', on_delete=django.db.models.deletion.SET_DEFAULT, to='main.employer'),
        ),
        migrations.AddField(
            model_name='deleteduser',
            name='region',
            field=models.ForeignKey(default='Other', on_delete=django.db.models.deletion.SET_DEFAULT, to='main.region'),
        ),
        migrations.AddField(
            model_name='deleteduser',
            name='vehicle',
            field=models.PositiveIntegerField(choices=[(243, 'Petrol'), (265, 'Diesel'), (192, 'Hybrid'), (98, 'Plug-in Hybrid'), (19, 'Electric'), (243, "Other / Don't know")], default=20),
            preserve_default=False,
        ),
    ]
