# Generated by Django 5.2 on 2025-05-18 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_deleteduser_distance_deleteduser_employer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='distance',
        ),
    ]
