# Generated by Django 5.2 on 2025-05-18 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_trip_distance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deletedtrip',
            name='distance',
        ),
    ]
