# Generated by Django 5.2 on 2025-06-08 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_deletedtrip_quantity_trip_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='All',
            fields=[
                ('name', models.CharField(primary_key=True, serialize=False, unique=True)),
                ('emissions_saved', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='employer',
            name='emissions_saved',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='region',
            name='emissions_saved',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='deletedtrip',
            name='mode',
            field=models.CharField(blank=True, choices=[('walk', 'Walk'), ('bike', 'Bike / Scooter'), ('bus', 'Bus'), ('ev', 'EV'), ('carpool', 'Carpool')], null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='mode',
            field=models.CharField(blank=True, choices=[('walk', 'Walk'), ('bike', 'Bike / Scooter'), ('bus', 'Bus'), ('ev', 'EV'), ('carpool', 'Carpool')], null=True),
        ),
    ]
