# Generated by Django 5.2 on 2025-06-14 03:40

import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_all_employer_emissions_saved_region_emissions_saved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', markdownx.models.MarkdownxField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
