# Generated by Django 5.2 on 2025-06-14 08:29

import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='logged_this_week',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=markdownx.models.MarkdownxField(help_text='Use markdown to style post (https://www.markdownguide.org/basic-syntax/). Do not use single hashtag heading (#) as is too large. Drag images in to add, as that will automatically store the image.'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='For system use only - will not be displayed to users.', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='age_group',
            field=models.CharField(choices=[('<13', 'Less than 13'), ('13-17', '13 - 17'), ('18-24', '18 - 24'), ('25-34', '25 - 34'), ('35-44', '35 - 44'), ('45-64', '45 - 64'), ('>65', 'More than 65'), ('prefer_not', 'Prefer not to say')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=320, unique=True),
        ),
    ]
