# Generated by Django 5.2 on 2025-06-14 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_squashed_0019_user_logged_this_week_alter_post_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletedtrip',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='deleteduser',
            name='distance',
            field=models.PositiveIntegerField(choices=[(500, '0.5km'), (1000, '1km'), (2500, '2.5km'), (5000, '5km'), (10000, '10km'), (25000, '25km'), (50000, '50km')]),
        ),
        migrations.AlterField(
            model_name='deleteduser',
            name='emissions_saved',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='deleteduser',
            name='vehicle',
            field=models.PositiveIntegerField(choices=[(243, 'Petrol'), (265, 'Diesel'), (192, 'Hybrid'), (98, 'Plug-in Hybrid'), (19, 'Electric'), (243, "Other / Don't know")]),
        ),
        migrations.AlterField(
            model_name='trip',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='distance',
            field=models.PositiveIntegerField(choices=[(500, '0.5km'), (1000, '1km'), (2500, '2.5km'), (5000, '5km'), (10000, '10km'), (25000, '25km'), (50000, '50km')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='vehicle',
            field=models.PositiveIntegerField(choices=[(243, 'Petrol'), (265, 'Diesel'), (192, 'Hybrid'), (98, 'Plug-in Hybrid'), (19, 'Electric'), (243, "Other / Don't know")]),
        ),
    ]
