# Generated by Django 5.2 on 2025-07-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_deletedtrip_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='trigger_email',
            field=models.BooleanField(default=False),
        ),
    ]
