# Generated by Django 5.2 on 2025-07-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_user_trigger_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='mode',
            field=models.CharField(blank=True, choices=[('walk', 'Walk'), ('bike', 'Bike / Scooter'), ('bus', 'Bus'), ('ev', 'EV'), ('carpool', 'Carpool'), ('wfh', 'Work from Home')], null=True),
        ),
    ]
