# Generated by Django 5.2 on 2025-08-07 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_trip_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.TextField()),
                ('html_body', models.TextField()),
                ('uuid', models.TextField()),
                ('priority', models.PositiveIntegerField()),
            ],
        ),
    ]
