# Generated by Django 5.2 on 2025-08-20 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_backedemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='last_logged_week',
            field=models.DateField(blank=True, null=True),
        ),
    ]
