# Generated by Django 5.2 on 2025-11-20 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='deletedtrip',
            name='distance',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='distance',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
