# Generated by Django 5.2 on 2026-09-17 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_deletedtrip_distance_trip_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='email',
            field=models.EmailField(max_length=320, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium'),
            preserve_default=False,
        ),
    ]
