# Generated by Django 5.2 on 2026-09-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_employer_email_employer_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=320),
            preserve_default=False,
        ),
    ]
